apiVersion: apps/v1
kind: Deployment
metadata:
  name: contoso-microservices-orders
  labels:
    app: contoso
    microservice: orders
spec:
  selector:
    matchLabels:
      app: contoso
      microservice: orders
  template:
    metadata:
      labels:
        app: contoso
        microservice: orders
    spec:
      containers:
      - name: orders-api
        image: ghcr.io/tomkerkhove/microservices-with-api-management-services-order:latest
        ports:
        - containerPort: 80
        env:
        - name: AZURESTORAGE_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
             name: orders-secrets
             key: AZURESTORAGE_CONNECTIONSTRING
        - name: SHIPMENTS_API_URI
          value: http://contoso-microservices-shipments-internal-service:88/api/v1/shipments
        livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 80
        readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: contoso-microservices-orders-loadbalancer-service
  labels:
    app: contoso
    microservice: orders
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: contoso-orders-api
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8889
      targetPort: 80
      protocol: TCP
  selector:
    app: contoso
    microservice: orders
---
apiVersion: v1
kind: Secret
metadata:
  name: orders-secrets
  labels:
    app: contoso
    microservice: orders
data:
  AZURESTORAGE_CONNECTIONSTRING: <base64 encoded connection string>